# workflow 이름
name: gaeha deployment

# workflow 트리거
on:
  # develop branch에 PR이 닫혔을 떄
  pull_request:
    types:
      - closed
    branches: [ "develop" ]

# workflow 권한
permissions:
  contents: read

# 작업 정의
jobs:
  build:
    name: build
    # 작업이 실행될 환경
    runs-on: ubuntu-latest
    # step 설정
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      # 시간대 설정
      - name: set up TimeZone
        run: |
          sudo timedatectl set-timezone Asia/Seoul

      # 권한 부여
      - name: Give permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: clean build

      - name: Upload jar file Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ApplicationJarFile
          path: build/libs/*.jar

      # ssh 접속
      - name: connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
      # 이전 파일 삭제
      - name: Remove previous jar file
        working-directory: gaeha
        run: rm -f *.jar
      # jar 파일
      - name: Download jar file from artifact
        uses: actions/download-artifact@v3
        with:
          name: ApplicationJarFile
          path: /gaeha
      # 배포
      - name: deploy to server
        working-directory: gaeha
        run: |
          echo "$DEV_DEPLOY_SCRIPT" > deploy.sh
          chmod 700 deploy.sh
          sudo ./deploy.sh
